{% set name = "openexr" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # The release tarball cannot be used from windows. Using the git repository
  # for the windows build.

  # Windows
  url: https://github.com/openexr/{{ name }}/archive/v{{ version }}.tar.gz  # [win]
  sha256: 4904c5ea7914a58f60a5e2fbc397be67e7a25c380d7d07c1c31a3eefff1c92f1  # [win]
  #patches:                                                                  # [win]
  #  - 0001-Imported-libraries-visibility.patch                              # [win]

  # Unix
  url: https://github.com/openexr/{{ name }}/archive/v{{ version }}.tar.gz
  #url: https://github.com/openexr/openexr/releases/download/v{{ version }}/{{ name|lower }}-{{ version }}.tar.gz  # [not win]
  sha256: 4904c5ea7914a58f60a5e2fbc397be67e7a25c380d7d07c1c31a3eefff1c92f1  # [not win]

build:
  number: 0000
  skip: True  # [win and vc<14]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=openexr
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - ilmbase
  run:
    - zlib
    - ilmbase

test:
  commands:
    - test -e $PREFIX/include/OpenEXR/OpenEXRConfig.h  # [unix]
    - test -e $PREFIX/include/OpenEXR/IlmBaseConfig.h  # [unix]
    - test -e $PREFIX/lib/libHalf$SHLIB_EXT            # [unix]
    - test -e $PREFIX/lib/libIexMath$SHLIB_EXT         # [unix]
    - test -e $PREFIX/lib/libIex$SHLIB_EXT             # [unix]
    - test -e $PREFIX/lib/libIlmImf$SHLIB_EXT          # [unix]
    - test -e $PREFIX/lib/libIlmImfUtil$SHLIB_EXT      # [unix]
    - test -e $PREFIX/lib/libIlmThread$SHLIB_EXT       # [unix]
    - test -e $PREFIX/lib/libImath$SHLIB_EXT           # [unix]

about:
  home: https://github.com/openexr/openexr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: |
    OpenEXR is a high dynamic-range (HDR) image file format developed by
    Industrial Light & Magic for use in computer imaging applications.
  description: |
    OpenEXR is a high dynamic-range (HDR) image file format developed by
    Industrial Light & Magic (ILM) for use in computer imaging applications. It
    supports stereoscopic and deep images. Weta Digital, Walt Disney Animation
    Studios, Sony Pictures Imageworks, Pixar Animation Studios, DreamWorks, and
    other studios, companies, and individuals have made contributions to the
    code base. The file format has seen wide adoption in a number of industries.
  doc_url: http://www.openexr.com/documentation.html
  dev_url: https://github.com/openexr/openexr

extra:
  recipe-maintainers:
    - aaronang
    - SylvainCorlay
    - wolfv
    - npavlovikj
    - JohanMabille
